// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ8m7cMfO3893_3IsdL4XPjOfyefUfXWU',
    appId: '1:384136880035:web:86c2032c05a53089988416',
    messagingSenderId: '384136880035',
    projectId: 'flutterddd-fda7b',
    authDomain: 'flutterddd-fda7b.firebaseapp.com',
    storageBucket: 'flutterddd-fda7b.appspot.com',
    measurementId: 'G-X03081KGZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASIetHA6nguQSPzAAdIlQEQbeaoVPcQb0',
    appId: '1:384136880035:android:9b63d02fa1cee323988416',
    messagingSenderId: '384136880035',
    projectId: 'flutterddd-fda7b',
    storageBucket: 'flutterddd-fda7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIUD6EdELsyVVjytyIPtC0EztedNNsKKM',
    appId: '1:384136880035:ios:c87f3e16779c55b9988416',
    messagingSenderId: '384136880035',
    projectId: 'flutterddd-fda7b',
    storageBucket: 'flutterddd-fda7b.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
